name: Syncing to the server
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: sigsoft
    steps:
      - name: 🔑 Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.HOST }}" > ~/.ssh/known_hosts

      - name: 🚀 Deploy using rsync
        run: rsync --archive --delete --stats -e 'ssh -p 7822' 'index.html' 'public_html/index.html'
      - run: echo "🖥️ We have just synchronized."
